#!/bin/sh
# Rebuilds aithing whenever anything under src/ changes. A running window
# notices its own binary is newer and execs the new one over itself, keeping
# the open session and whatever is typed in the composer, so this plus one
# open window is the whole edit-run loop.
#
#   ./dev.sh &        # then edit; the window follows along
#
# Nothing here talks to the window: the build is the signal. `./build.sh` by
# hand, or from an agent editing the source, reloads it just the same.
set -e
cd "$(dirname "$0")"

stamp() {
	# One line per file, so a change, a new file and a deletion all move it.
	# protocol.odin is regenerated by every build; watching it would make the
	# loop feed itself.
	find src -type f \( -name '*.odin' -o -name '*.vert' -o -name '*.frag' \) \
		! -path 'src/wayland/protocol.odin' -printf '%p %T@\n' | sort
}

last=$(stamp)
echo "watching src/ — build once now"
./build.sh || true

while :; do
	sleep 0.3
	now=$(stamp)
	[ "$now" = "$last" ] && continue
	last=$now
	# Let a burst of writes finish before spending a build on the first one.
	sleep 0.2
	last=$(stamp)
	printf '\n--- %s ---\n' "$(date +%H:%M:%S)"
	./build.sh || echo "build failed; the running window keeps the old one"
done
